name: Generate index

on:
  push:
    branches: 'experimental'
    paths:
      - 'localized_data/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: Merge changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git merge -X theirs origin/experimental

      - uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Create index
        run: python gen_index.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update index
          branch: release
          file_pattern: 'index.json'

      - name: Send update
        if: ${{ vars.NOTIFY_REPO }}
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.UPD_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2026-03-10" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ vars.NOTIFY_REPO }}/actions/workflows/release.yml/dispatches \
          -d '{"ref":"main"}'